// app/layout.tsx
import { ReactNode } from 'react';
import i18nConfig from '../../../i18nConfig';
import initTranslations from '../i18n';
import TranslationsProvider from '../../components/TranslationsProvider';
import Header from '../../components/Header';
import '../globals.css';

export async function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
  params
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  const { resources } = await initTranslations(params.locale, ['default']);

  return (
    <html lang={params.locale} dir={params.locale === 'ar' ? 'rtl' : 'ltr'}>
      <body style={{ margin: 0, padding: 0, boxSizing: 'border-box' }}>
        <TranslationsProvider locale={params.locale} namespaces={['default']} resources={resources}>
          <Header initialLanguage={params.locale} />
          {children}
        </TranslationsProvider>
      </body>
    </html>
  )
}